
#
# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.7 conda env create --file docs/conda-recipe.yaml
#

name: daxbench-docs

channels:
  - defaults
  - conda-forge

dependencies:
  - python = 3.10
  - pip

  # Learning
  - pip:
      - sphinxcontrib-katex  # for documentation

  # Build toolchain


  # Documentation
  - sphinx >= 5.2.1
  - sphinx-rtd-theme
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinxcontrib-spelling
  - sphinxcontrib-bibtex
  - sphinx-autodoc-typehints >= 1.19.2
  - pyenchant
  - hunspell-en
  - myst-nb
  - ipykernel
  - pandoc
  - docutils
